Repository cross-rs/cross, pull requests merged in 2019-08, with the labels that each got.

#285 Simplify `if let`.
  src/docker.rs
Labels: S-waiting-on-review

#255 Stop hard-coding NEON support for armv7-unknown-linux-musleabihf.
  docker/armv7-unknown-linux-musleabihf/Dockerfile
Labels: T-tools

#251 Support mounting on SELinux
  src/docker.rs
Labels: S-blocked, T-tools

#271 Minor improvements to wording
  README.md
Labels: S-waiting-on-review

#288 Fix Travis deployment.
  .travis.yml
Labels: S-waiting-on-review

#290 Fix `before_deploy.sh`.
  ci/before_deploy.sh
Labels: S-waiting-on-review

#230 Update emscripten
  docker/emscripten.sh
Labels: S-blocked
