Repository cross-rs/cross, pull requests merged in 2022-09, with the labels that each got.

#1011 Fix documentation issues
  README.md
  docs/cross_toml.md
Labels: docs-problem, no changelog

#1007 volume improvements
  src/bin/commands/containers.rs
  src/bin/commands/images.rs
  src/bin/cross-util.rs
  src/build.rs
  src/cargo.rs
  src/docker/custom.rs
  src/docker/image.rs
  src/docker/local.rs
  src/docker/remote.rs
  src/docker/shared.rs
  src/file.rs
  src/lib.rs
  src/rustc.rs
  src/rustup.rs
  xtask/src/build_docker_image.rs
  xtask/src/ci.rs
  xtask/src/hooks.rs
  xtask/src/target_info.rs
Labels: no changelog

#1019 mention Getting Started
  README.md
Labels: no changelog

#1018 Update deny list to all system packages for ARMv6 HF.
  .changes/1018.json
  docker/Dockerfile.arm-unknown-linux-gnueabihf
  docker/deny-debian-packages.sh
Labels: enhancement, container-images, A-arm

#1022 Support docker images with targets containing `.`s.
  xtask/src/util.rs
Labels: meta, no changelog, no-ci-targets

#1024 Fixing superfluous download of pre-built target rust-std when build-s…
  .changes/1024.json
  src/lib.rs
Labels: enhancement

#1027 bump dependencies and lockfile
  Cargo.lock
  Cargo.toml
  deny.toml
  xtask/Cargo.toml
Labels: no changelog

#1008 convert and improve matrix generation with a xtask script
  .github/workflows/ci.yml
  Cargo.lock
  src/docker/provided_images.rs
  targets.toml
  xtask/Cargo.toml
  xtask/src/build_docker_image.rs
  xtask/src/ci.rs
  xtask/src/ci/target_matrix.rs
  xtask/src/codegen.rs
  xtask/src/util.rs
Labels: no changelog

#1036 Fix Wine install steps from WineHQ.
  docker/wine.sh
Labels: container-images, no changelog, A-windows, A-wine

#1032 Allow disabling buildkit for engines lacking support.
  .changes/1032.json
  src/config.rs
  src/docker/custom.rs
  src/docker/engine.rs
  xtask/src/build_docker_image.rs
Labels: enhancement, A-container-engine
