Repository cross-rs/cross, pull requests merged in 2022-07, with the labels that each got.

#890 Support rootless docker.
  CHANGELOG.md
  src/docker/shared.rs
Labels: enhancement, A-container-engine

#891 Add manual overrides for container user namespaces.
  CHANGELOG.md
  src/docker/local.rs
  src/docker/remote.rs
  src/docker/shared.rs
Labels: enhancement, feature-request

#892 fix flag and naming of coverage report
  .github/workflows/ci.yml
Labels: no changelog

#895 Fix tag names for custom docker images.
  CHANGELOG.md
  src/docker/custom.rs
Labels: bug, A-container-engine

#897 Fix build/target config file ordering
  CHANGELOG.md
  src/config.rs
  src/cross_toml.rs
Labels: bug, A-config

#900 Enable skipping of copying build artifacts back to host.
  CHANGELOG.md
  src/docker/remote.rs
Labels: enhancement

#898 Bug fix for mounted paths for docker-in-docker.
  CHANGELOG.md
  src/docker/shared.rs
Labels: bug

#904 Various bug fixes for cross.
  CHANGELOG.md
  src/cargo.rs
  src/docker/local.rs
  src/docker/mod.rs
  src/docker/remote.rs
  src/docker/shared.rs
  src/shell.rs
Labels: bug

#873 Add integration tests.
  .github/workflows/ci.yml
  ci/shared.sh
  ci/test-bisect.sh
  ci/test-docker-in-docker.sh
  ci/test-remote.sh
  ci/test.sh
  src/bin/commands/containers.rs
  src/docker/shared.rs
Labels: meta, no changelog

#907 wiki check toml
  .github/workflows/weekly.yml
  README.md
  src/tests/toml.rs
Labels: no changelog

#908 Use create_dir_all for cargo directory.
  src/docker/shared.rs
Labels: bug, no changelog

#878 Add dockerfile for cross.
  .github/workflows/ci.yml
  CHANGELOG.md
  ci/test-cross-image.sh
  docker/Dockerfile.cross
  docker/cross.sh
  xtask/src/build_docker_image.rs
  xtask/src/ci.rs
  xtask/src/util.rs
Labels: enhancement, container-images

#911 Structify more of the internals to simplify the implementation.
  src/bin/commands/clean.rs
  src/bin/commands/containers.rs
  src/bin/commands/images.rs
  src/bin/cross-util.rs
  src/cargo.rs
  src/cli.rs
  src/config.rs
  src/cross_toml.rs
  src/docker/custom.rs
  src/docker/engine.rs
  src/docker/local.rs
  src/docker/mod.rs
  src/docker/remote.rs
  src/docker/shared.rs
  src/extensions.rs
  src/lib.rs
  src/rustc.rs
  src/rustup.rs
  src/shell.rs
  src/tests.rs
  src/tests/toml.rs
  xtask/src/build_docker_image.rs
  xtask/src/ci.rs
  xtask/src/crosstool.rs
  xtask/src/hooks.rs
  xtask/src/install_git_hooks.rs
  xtask/src/main.rs
  xtask/src/target_info.rs
  xtask/src/util.rs
Labels: meta, no changelog

#915 more clippy
  clippy.toml
  src/cargo.rs
  src/cli.rs
  src/config.rs
  src/cross_toml.rs
  src/docker/custom.rs
  src/docker/engine.rs
  src/docker/local.rs
  src/docker/remote.rs
  src/docker/shared.rs
  src/errors.rs
  src/extensions.rs
  src/file.rs
  src/id.rs
  src/lib.rs
  src/rustc.rs
  src/rustup.rs
  src/shell.rs
  src/temp.rs
  src/tests.rs
  src/tests/toml.rs
Labels: no changelog

#921 Support cargo term variables.
  CHANGELOG.md
  src/bin/commands/clean.rs
  src/bin/commands/containers.rs
  src/bin/commands/images.rs
  src/cli.rs
  src/shell.rs
  xtask/src/build_docker_image.rs
  xtask/src/crosstool.rs
  xtask/src/hooks.rs
  xtask/src/install_git_hooks.rs
  xtask/src/target_info.rs
Labels: enhancement

#925 fix dind test
  .github/workflows/ci.yml
  ci/test-cross-image.sh
  ci/test-docker-in-docker.sh
Labels: no changelog

#926 fix for real
  .github/workflows/ci.yml
  ci/test-cross-image.sh
  ci/test-docker-in-docker.sh
Labels: no changelog

#923 release version 0.2.3
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: release

#927 don't skip publish when integration tests are not run
  .github/workflows/ci.yml
Labels: no changelog

#930 Fix `is_verbose` accepting any 1-character argument.
  CHANGELOG.md
  src/cli.rs
Labels: bug

#929 fix verbose
  CHANGELOG.md
  src/extensions.rs
Labels: bug

#933 Deny installation of conflicting Debian packages.
  .changes/931.json
  CHANGELOG.md
  docker/Dockerfile.aarch64-unknown-linux-gnu
  docker/Dockerfile.arm-unknown-linux-gnueabi
  docker/Dockerfile.armv5te-unknown-linux-gnueabi
  docker/Dockerfile.armv7-unknown-linux-gnueabihf
  docker/Dockerfile.mips64-unknown-linux-gnuabi64
  docker/Dockerfile.mips64el-unknown-linux-gnuabi64
  docker/Dockerfile.mipsel-unknown-linux-gnu
  docker/Dockerfile.powerpc-unknown-linux-gnu
  docker/Dockerfile.powerpc64-unknown-linux-gnu
  docker/Dockerfile.powerpc64le-unknown-linux-gnu
  docker/Dockerfile.riscv64gc-unknown-linux-gnu
  docker/Dockerfile.s390x-unknown-linux-gnu
  docker/Dockerfile.sparc64-unknown-linux-gnu
  docker/deny-debian-packages.sh
Labels: enhancement

#934 Add support for pre-build hooks with remote docker.
  .changes/934.json
  src/docker/remote.rs
  src/docker/shared.rs
Labels: enhancement

#937 Support Windows-style manifest paths.
  .changes/937.json
  src/cli.rs
Labels: bug

#939 Fix cross when using absolute paths to the current project.
  .changes/939.json
  src/docker/local.rs
  src/docker/remote.rs
  src/docker/shared.rs
Labels: bug

#940 check for newlines in test
  rustfmt.yml
  src/lib.rs
  src/tests.rs
  src/tests/toml.rs
Labels: no changelog

#941 replace walkdir with ripgreps ignore crate
  .github/actions/setup-rust/action.yml
  Cargo.lock
  Cargo.toml
  ci/test-bisect.sh
  src/tests.rs
  src/tests/toml.rs
Labels: no changelog

#945 Fix pre-build Docker image names with Podman.
  .changes/945.json
  src/docker/custom.rs
Labels: bug, A-container-engine

#817 Enable usage of other toolchains in images
  .changes/817.json
  .github/workflows/ci.yml
  Cargo.toml
  README.md
  ci/shared.sh
  ci/test-bisect.sh
  ci/test-cross-image.sh
  ci/test-docker-in-docker.sh
  ci/test-foreign-toolchain.sh
  ci/test-remote.sh
  ci/test.sh
  docs/cross_toml.md
  src/bin/commands/containers.rs
  src/bin/cross-util.rs
  src/bin/cross.rs
  src/build.rs
  src/config.rs
  src/cross_toml.rs
  src/docker/custom.rs
  src/docker/engine.rs
  src/docker/image.rs
  src/docker/local.rs
  src/docker/mod.rs
  src/docker/provided_images.rs
  src/docker/remote.rs
  src/docker/shared.rs
  src/lib.rs
  src/rustc.rs
  src/rustup.rs
  src/tests.rs
  xtask/src/build_docker_image.rs
  xtask/src/ci.rs
  xtask/src/codegen.rs
  xtask/src/main.rs
  xtask/src/target_info.rs
  xtask/src/util.rs
Labels: enhancement, breaking change, A-aarch64-host

#950 Fix FreeBSD migration to `.pkg` extensions.
  docker/Dockerfile.i686-unknown-freebsd
  docker/Dockerfile.x86_64-unknown-freebsd
  docker/freebsd-common.sh
  docker/freebsd-extras.sh
  docker/freebsd-install.sh
  docker/freebsd.sh
Labels: bug

#947 Resolve symlinks for cargo and xargo home.
  .changes/947.json
  src/bin/commands/containers.rs
  src/docker/image.rs
  src/docker/local.rs
  src/docker/remote.rs
  src/docker/shared.rs
  src/file.rs
  src/lib.rs
Labels: bug

#591 Update all GNU docker images to latest LTS version on Docker.
  .changes/591.json
  .github/workflows/ci.yml
  README.md
  docker/Dockerfile.aarch64-unknown-linux-gnu
  docker/Dockerfile.aarch64-unknown-linux-musl
  docker/Dockerfile.arm-unknown-linux-gnueabi
  docker/Dockerfile.arm-unknown-linux-gnueabihf
  docker/Dockerfile.arm-unknown-linux-musleabi
  docker/Dockerfile.arm-unknown-linux-musleabihf
  docker/Dockerfile.armv5te-unknown-linux-gnueabi
  docker/Dockerfile.armv5te-unknown-linux-musleabi
  docker/Dockerfile.armv7-unknown-linux-gnueabi
  docker/Dockerfile.armv7-unknown-linux-gnueabihf
  docker/Dockerfile.armv7-unknown-linux-musleabi
  docker/Dockerfile.i586-unknown-linux-gnu
  docker/Dockerfile.i586-unknown-linux-musl
  docker/Dockerfile.i686-pc-windows-gnu
  docker/Dockerfile.i686-unknown-freebsd
  docker/Dockerfile.i686-unknown-linux-gnu
  docker/Dockerfile.i686-unknown-linux-musl
  docker/Dockerfile.mips-unknown-linux-gnu
  docker/Dockerfile.mips-unknown-linux-musl
  docker/Dockerfile.mips64-unknown-linux-gnuabi64
  docker/Dockerfile.mips64-unknown-linux-muslabi64
  docker/Dockerfile.mips64el-unknown-linux-gnuabi64
  docker/Dockerfile.mips64el-unknown-linux-muslabi64
  docker/Dockerfile.mipsel-unknown-linux-gnu
  docker/Dockerfile.mipsel-unknown-linux-musl
  docker/Dockerfile.powerpc-unknown-linux-gnu
  docker/Dockerfile.powerpc64-unknown-linux-gnu
  docker/Dockerfile.powerpc64le-unknown-linux-gnu
  docker/Dockerfile.riscv64gc-unknown-linux-gnu
  docker/Dockerfile.s390x-unknown-linux-gnu
  docker/Dockerfile.sparc64-unknown-linux-gnu
  docker/Dockerfile.sparcv9-sun-solaris
  docker/Dockerfile.thumbv6m-none-eabi
  docker/Dockerfile.thumbv7em-none-eabi
  docker/Dockerfile.thumbv7em-none-eabihf
  docker/Dockerfile.thumbv7m-none-eabi
  docker/Dockerfile.thumbv7neon-unknown-linux-gnueabihf
  docker/Dockerfile.x86_64-pc-windows-gnu
  docker/Dockerfile.x86_64-sun-solaris
  docker/Dockerfile.x86_64-unknown-dragonfly
  docker/Dockerfile.x86_64-unknown-freebsd
  docker/Dockerfile.x86_64-unknown-linux-gnu
  docker/Dockerfile.x86_64-unknown-linux-gnu.centos
  docker/Dockerfile.x86_64-unknown-netbsd
  docker/dragonfly.sh
  docker/linux-image.sh
  docker/mingw.sh
  docker/solaris.sh
  src/docker/shared.rs
Labels: container-images, breaking change

#942 Use non-canonical paths for mount paths.
  .changes/942.json
  src/cli.rs
  src/docker/local.rs
  src/docker/remote.rs
  src/docker/shared.rs
  src/file.rs
Labels: bug, enhancement

#554 Add `--force-non-host` flag.
  .changes/554.json
  Cargo.lock
  Cargo.toml
  src/rustup.rs
Labels: upstream

#880 Add a `zig cc`-based image.
  .changes/880.json
  .github/workflows/ci.yml
  ci/test-zig-image.sh
  docker/Dockerfile.zig
  docker/zig.sh
  docs/cross_toml.md
  src/config.rs
  src/cross_toml.rs
  src/docker/custom.rs
  src/docker/local.rs
  src/docker/provided_images.rs
  src/docker/remote.rs
  src/docker/shared.rs
  src/lib.rs
  xtask/src/codegen.rs
  xtask/src/util.rs
Labels: enhancement, container-images

#962 Fix SELinux labels to allow shared use.
  .changes/962.json
  src/docker/local.rs
Labels: bug

#946 Ignore tests that touch the filesystem if sandboxed.
  src/build.rs
  src/docker/shared.rs
Labels: no changelog

#971 Fix changelog check for no changes.
  .github/workflows/changelog.yml
Labels: meta, no changelog

#978 Update macOS CI version.
  .github/workflows/ci.yml
Labels: meta, no changelog

#974 Change `mips64-unknown-linux-gnuabi64` to hard-float.
  .changes/974.json
  .github/workflows/ci.yml
  docker/Dockerfile.mips64-unknown-linux-muslabi64
  docker/mips64-linux-muslabi64-gcc.sh
Labels: bug, container-images, A-musl, A-mips

#979 Add mirrors for file downloads.
  docker/dragonfly.sh
  docker/dropbear.sh
  docker/freebsd.sh
  docker/illumos.sh
  docker/lib.sh
  docker/netbsd.sh
  docker/solaris.sh
Labels: container-images, no changelog

#967 use new color-eyre function to optionally display location section
  Cargo.lock
  Cargo.toml
  src/docker/shared.rs
  src/errors.rs
  src/lib.rs
Labels: no changelog

#980 Add qemu-user runners for s390x and sparc64 to Github workflow.
  .github/workflows/ci.yml
Labels: meta, no changelog

#981 Warn if both remote and docker-in-docker are set.
  src/docker/remote.rs
Labels: no changelog

#984 Add Linux images for `riscv64gc-unknown-linux-gnu`.
  .changes/984.json
  .github/workflows/ci.yml
  docker/Dockerfile.riscv64gc-unknown-linux-gnu
  docker/linux-image.sh
  docker/linux-runner
Labels: container-images, A-arm, A-riscv
