Repository cross-rs/cross, pull requests merged in 2022-11, with the labels that each got.

#1021 Allow CI without requiring targets to be built/tested.
  .github/workflows/ci.yml
  xtask/src/ci/target_matrix.rs
  xtask/src/util.rs
Labels: meta, no changelog, no-ci-targets

#1105 Explicitly prefer `-ar` to `-gcc-ar`.
  .changes/1105.json
  docker/Dockerfile.i686-unknown-freebsd
  docker/Dockerfile.sparcv9-sun-solaris
  docker/Dockerfile.thumbv6m-none-eabi
  docker/Dockerfile.thumbv7em-none-eabi
  docker/Dockerfile.thumbv7em-none-eabihf
  docker/Dockerfile.thumbv7m-none-eabi
  docker/Dockerfile.x86_64-sun-solaris
  docker/Dockerfile.x86_64-unknown-dragonfly
  docker/Dockerfile.x86_64-unknown-freebsd
  docker/Dockerfile.x86_64-unknown-netbsd
Labels: bug, container-images, A-bsd, A-newlib, A-solaris

#1023 Add support for Android versions 5-11.
  .changes/1023.json
  .gitignore
  Cargo.lock
  docker/.dockerignore
  docker/Dockerfile.aarch64-linux-android
  docker/Dockerfile.arm-linux-androideabi
  docker/Dockerfile.armv7-linux-androideabi
  docker/Dockerfile.i686-linux-android
  docker/Dockerfile.thumbv7neon-linux-androideabi
  docker/Dockerfile.x86_64-linux-android
  docker/android-ndk.sh
  docker/android-runner
  docker/android-symlink.sh
  docker/android-system.sh
  docker/android/README.md
  docker/android/android/__init__.py
  docker/android/android/make.py
  docker/android/android/soong.py
  docker/android/android/util.py
  docker/android/pyproject.toml
  docker/android/scripts/build-system.py
  docker/android/tests/Addition.bp
  docker/android/tests/Android.bp
  docker/android/tests/Android.mk
  docker/android/tests/Comments.mk
  docker/android/tests/Empty.bp
  docker/android/tests/Empty.mk
  docker/android/tests/FakeTitle.mk
  docker/android/tests/Grouped.mk
  docker/android/tests/ListMap.bp
  docker/android/tests/Multiline.mk
  docker/android/tests/Nested.mk
  docker/android/tests/NonTest.bp
  docker/android/tests/README.md
  docker/android/tests/Single.mk
  docker/android/tests/test_make.py
  docker/android/tests/test_metadata.py
  docker/android/tests/test_soong.py
  docker/android/tests/test_util.py
  docker/android/tox.ini
  docker/validate-android-args.sh
  src/rustc.rs
  xtask/Cargo.toml
  xtask/src/hooks.rs
  xtask/src/main.rs
Labels: enhancement, container-images, A-android

#1111 Update zig-cc and zigbuild versions.
  .changes/880-1111.json
  .changes/880.json
  ci/test-zig-image.sh
  docker/zig.sh
Labels: enhancement, container-images

#1120 Update documentation on environment variable passthrough.
  README.md
Labels: docs-problem, no changelog, no-ci-targets

#1127 Update rust-cache version.
  .github/actions/setup-rust/action.yml
Labels: meta, no changelog, no-ci-targets

#1125 Always link to libc when compiling musl targets.
  .changes/1063-1125.json
  docker/Dockerfile.arm-unknown-linux-musleabi
  docker/Dockerfile.arm-unknown-linux-musleabihf
  docker/Dockerfile.armv7-unknown-linux-musleabi
  docker/Dockerfile.armv7-unknown-linux-musleabihf
  docker/Dockerfile.i586-unknown-linux-musl
  docker/Dockerfile.i686-unknown-linux-musl
  docker/Dockerfile.mips-unknown-linux-musl
  docker/Dockerfile.mipsel-unknown-linux-musl
  docker/Dockerfile.x86_64-unknown-linux-musl
  docker/aarch64-linux-musl-gcc.sh
  docker/musl-gcc.sh
  docker/rust-1-65-musl-gcc.sh
  src/docker/shared.rs
Labels: regression, c-cpp-deps-issue, container-images, A-musl

#1123 Use MinGW GCC with POSIX thread support when linking.
  .changes/1123.json
  .changes/591-1095.json
  docker/Dockerfile.i686-pc-windows-gnu
  docker/Dockerfile.x86_64-pc-windows-gnu
  docker/wine.sh
Labels: enhancement, c-cpp-deps-issue, breaking change, A-windows, A-wine

#1131 Fix progress clap parsing.
  xtask/src/build_docker_image.rs
Labels: no changelog, no-ci-targets

#1130 Fix clippy lints on latest nightly.
  src/cross_toml.rs
  src/docker/remote.rs
  src/docker/shared.rs
Labels: no changelog, no-ci-targets

#1133 Remove unused CentOS file for x86_64.
  docker/Dockerfile.x86_64-unknown-linux-gnu.centos
Labels: no changelog

#1135 CI: Fix most deprecation warnings from GitHub Actions
  .github/actions/cargo-install-upload-artifacts/action.yml
  .github/actions/cargo-llvm-cov/action.yml
  .github/actions/cargo-publish/action.yml
  .github/actions/post/main.js
  .github/actions/setup-rust/action.yml
  .github/workflows/changelog.yml
  .github/workflows/ci.yml
  .github/workflows/weekly.yml
  xtask/src/build_docker_image.rs
  xtask/src/ci.rs
  xtask/src/ci/target_matrix.rs
  xtask/src/util.rs
Labels: meta

#1139 CI: Fix changelog check
  .github/workflows/changelog.yml
Labels: meta, no changelog

#1142 Ensure ignored CLI arguments to cross are always passed at the end.
  .changes/1049-1142.json
  src/cli.rs
  src/lib.rs
Labels: bug

#1151 Replace atty with is-terminal.
  Cargo.lock
  Cargo.toml
  deny.toml
  src/shell.rs
Labels: no changelog, no-ci-targets

#1149 Add a comment for how the Dockerfile path is resolved.
  src/docker/custom.rs
Labels: meta, no changelog, no-ci-targets

#1154 be more explicit about eol
  .gitattributes
  docker/.gitattributes
Labels: meta, no changelog, no-ci-targets

#1160 Don't warn when toolchain version is explicitly provided.
  .changes/1160.json
  src/lib.rs
Labels: feature-request, no-ci-targets

#1091 improve weekly checks and push the resulting images
  .github/workflows/weekly.yml
  xtask/src/ci.rs
  xtask/src/ci/target_matrix.rs
Labels: no changelog, no-ci-targets

#1132 Add C++ exception support to FreeBSD targets.
  .changes/1028-1132.json
  docker/freebsd-common.sh
  docker/freebsd.sh
Labels: c-cpp-deps-issue, container-images, no changelog, A-bsd

#1134 Use a linker script for libstdc++.
  .changes/1063-1125-1134.json
  docker/Dockerfile.aarch64-unknown-linux-musl
  docker/Dockerfile.arm-unknown-linux-musleabi
  docker/Dockerfile.arm-unknown-linux-musleabihf
  docker/Dockerfile.armv5te-unknown-linux-musleabi
  docker/Dockerfile.armv7-unknown-linux-musleabi
  docker/Dockerfile.armv7-unknown-linux-musleabihf
  docker/Dockerfile.i586-unknown-linux-musl
  docker/Dockerfile.i686-unknown-linux-musl
  docker/Dockerfile.mips-unknown-linux-musl
  docker/Dockerfile.mips64-unknown-linux-muslabi64
  docker/Dockerfile.mips64el-unknown-linux-muslabi64
  docker/Dockerfile.mipsel-unknown-linux-musl
  docker/Dockerfile.x86_64-unknown-linux-musl
  docker/aarch64-linux-musl-gcc.sh
  docker/musl-gcc.sh
  docker/musl-symlink.sh
  docker/rust-1-65-musl-gcc.sh
  docker/rustc_info.sh
Labels: c-cpp-deps-issue, container-images, A-musl

#1157 Fix mount paths on Windows.
  .changes/1057.json
  ci/shared.sh
  ci/test-bisect.sh
  ci/test-foreign-toolchain.sh
  ci/test-podman.sh
  ci/test-remote.sh
  ci/test-zig-image.sh
  ci/test.sh
  src/docker/local.rs
  src/file.rs
Labels: bug, A-windows-host

#1164 Add package site mirrors for FreeBSD.
  .changes/1164.json
  docker/freebsd-common.sh
  docker/freebsd-extras.sh
  docker/freebsd-install.sh
  docker/freebsd.sh
Labels: A-bsd
