Repository cross-rs/cross, pull requests merged in 2022-10, with the labels that each got.

#1040 Document --cache-from limitations with podman.
  xtask/src/build_docker_image.rs
Labels: meta, no changelog

#1039 Add support for other overlay filesystems.
  .changes/1039.json
  src/docker/shared.rs
Labels: A-container-engine

#951 remove actions-rs
  .github/actions/cargo-install-upload-artifacts/action.yml
  .github/actions/cargo-publish/action.yml
  .github/actions/setup-rust/action.yml
  .github/actions/setup-rust/rust.json
  .github/workflows/ci.yml
  src/lib.rs
Labels: no changelog

#1042 fix `cargo llvm-cov` to use new `report` subcommand
  .github/actions/cargo-llvm-cov/action.yml
Labels: meta, no changelog

#1044 Document remote container termination safety guarantees.
  src/errors.rs
Labels: no changelog

#1047 Provide fallback for rustc version when envvars not present.
  docker/Dockerfile.aarch64-unknown-linux-musl
  docker/Dockerfile.armv5te-unknown-linux-musleabi
  docker/Dockerfile.mips64-unknown-linux-muslabi64
  docker/Dockerfile.mips64el-unknown-linux-muslabi64
  docker/aarch64-linux-musl-gcc.sh
  docker/arm-linux-musleabi-gcc.sh
  docker/mips64-linux-musl-gcc.sh
  docker/mips64el-linux-musl-gcc.sh
  docker/rustc_info.sh
Labels: enhancement, container-images, no changelog

#1051 remove .git on binary installation
  .github/actions/cargo-install-upload-artifacts/action.yml
Labels: bug, no changelog

#1057 suggest that buildx needs to be available
  src/bin/commands/images.rs
  src/docker/custom.rs
  src/docker/engine.rs
Labels: no changelog

#1059 Ensure successful CI conclusion with empty matrix.
  .github/workflows/ci.yml
  xtask/src/ci/target_matrix.rs
Labels: meta, no changelog

#1038 upgrade to clap 4.0
  .changes/1038.json
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  README.md
  xtask/Cargo.toml
  xtask/src/ci/target_matrix.rs
Labels: no changelog

#1064 add `CROSS_BUILD_OPTS` and `--build-opts` to enable passing more flags
  xtask/src/build_docker_image.rs
Labels: meta, no changelog

#1065 Workaround for slow CentOS builds depending on the ulimit.
  docker/aarch64-linux-gnu-glibc.sh
  docker/lib.sh
  docker/qemu.sh
Labels: upstream, meta, no changelog

#1054 Allow Persistent Data Volume to be Created Outside of Package
  .changes/1054.json
  src/bin/commands/containers.rs
  src/docker/local.rs
  src/docker/remote.rs
  src/docker/shared.rs
Labels: enhancement

#1070 Warn when mounted volume likely uses a path rather than an environment variable.
  src/docker/local.rs
  src/docker/remote.rs
  src/docker/shared.rs
Labels: enhancement, no changelog

#1071 Terminate child containers on program termination.
  src/bin/commands/containers.rs
  src/docker/local.rs
  src/docker/mod.rs
  src/docker/remote.rs
  src/docker/shared.rs
  src/errors.rs
Labels: bug, regression, no changelog

#1072 Fix persistent data volumes with remote cross.
  src/bin/commands/containers.rs
  src/bin/commands/images.rs
  src/docker/custom.rs
  src/docker/local.rs
  src/docker/remote.rs
  src/docker/shared.rs
  src/errors.rs
  src/lib.rs
  xtask/src/build_docker_image.rs
  xtask/src/target_info.rs
  xtask/src/util.rs
Labels: bug, regression, no changelog

#1073 Passthrough cross environment variables by default.
  .changes/1073.json
  src/docker/shared.rs
Labels: enhancement

#1078 Fix custom image names for images with a trailing '-' character.
  .changes/1078.json
  src/docker/custom.rs
Labels: bug

#1080 Add `CROSS_SYSROOT` envvar to specify target sysroot.
  docker/Dockerfile.aarch64-linux-android
  docker/Dockerfile.aarch64-unknown-linux-gnu
  docker/Dockerfile.aarch64-unknown-linux-gnu.centos
  docker/Dockerfile.aarch64-unknown-linux-musl
  docker/Dockerfile.arm-linux-androideabi
  docker/Dockerfile.arm-unknown-linux-gnueabi
  docker/Dockerfile.arm-unknown-linux-gnueabihf
  docker/Dockerfile.arm-unknown-linux-musleabi
  docker/Dockerfile.arm-unknown-linux-musleabihf
  docker/Dockerfile.armv5te-unknown-linux-gnueabi
  docker/Dockerfile.armv5te-unknown-linux-musleabi
  docker/Dockerfile.armv7-linux-androideabi
  docker/Dockerfile.armv7-unknown-linux-gnueabi
  docker/Dockerfile.armv7-unknown-linux-gnueabihf
  docker/Dockerfile.armv7-unknown-linux-musleabi
  docker/Dockerfile.armv7-unknown-linux-musleabihf
  docker/Dockerfile.asmjs-unknown-emscripten
  docker/Dockerfile.i586-unknown-linux-gnu
  docker/Dockerfile.i586-unknown-linux-musl
  docker/Dockerfile.i686-linux-android
  docker/Dockerfile.i686-pc-windows-gnu
  docker/Dockerfile.i686-unknown-freebsd
  docker/Dockerfile.i686-unknown-linux-gnu
  docker/Dockerfile.i686-unknown-linux-musl
  docker/Dockerfile.mips-unknown-linux-gnu
  docker/Dockerfile.mips-unknown-linux-musl
  docker/Dockerfile.mips64-unknown-linux-gnuabi64
  docker/Dockerfile.mips64-unknown-linux-muslabi64
  docker/Dockerfile.mips64el-unknown-linux-gnuabi64
  docker/Dockerfile.mips64el-unknown-linux-muslabi64
  docker/Dockerfile.mipsel-unknown-linux-gnu
  docker/Dockerfile.mipsel-unknown-linux-musl
  docker/Dockerfile.native
  docker/Dockerfile.native.centos
  docker/Dockerfile.powerpc-unknown-linux-gnu
  docker/Dockerfile.powerpc64-unknown-linux-gnu
  docker/Dockerfile.powerpc64le-unknown-linux-gnu
  docker/Dockerfile.riscv64gc-unknown-linux-gnu
  docker/Dockerfile.s390x-unknown-linux-gnu
  docker/Dockerfile.sparc64-unknown-linux-gnu
  docker/Dockerfile.sparcv9-sun-solaris
  docker/Dockerfile.thumbv7neon-linux-androideabi
  docker/Dockerfile.thumbv7neon-unknown-linux-gnueabihf
  docker/Dockerfile.wasm32-unknown-emscripten
  docker/Dockerfile.x86_64-linux-android
  docker/Dockerfile.x86_64-pc-windows-gnu
  docker/Dockerfile.x86_64-sun-solaris
  docker/Dockerfile.x86_64-unknown-dragonfly
  docker/Dockerfile.x86_64-unknown-freebsd
  docker/Dockerfile.x86_64-unknown-illumos
  docker/Dockerfile.x86_64-unknown-linux-gnu
  docker/Dockerfile.x86_64-unknown-linux-gnu.centos
  docker/Dockerfile.x86_64-unknown-linux-musl
  docker/Dockerfile.x86_64-unknown-netbsd
Labels: enhancement, no changelog

#1086 Fix typo in aarch64-linux-android Dockerfile
  docker/Dockerfile.aarch64-linux-android
Labels: no changelog

#1084 Fix remote docker paths on Windows hosts.
  .changes/1084.json
  src/bin/commands/containers.rs
  src/docker/remote.rs
Labels: bug, A-remote

#1015 Improve error diagnostics and other changes
  .gitattributes
  ci/test-remote.sh
  src/bin/commands/containers.rs
  src/bin/commands/images.rs
  src/bin/cross.rs
  src/docker/remote.rs
  src/docker/shared.rs
  src/extensions.rs
  src/lib.rs
  src/shell.rs
Labels: no changelog

#1085 Fixes custom toolchain support without rustup.
  .changes/1085.json
  src/docker/shared.rs
  src/lib.rs
  src/rustc.rs
  src/tests.rs
Labels: enhancement

#1087 Support crosstool for uclibc, musl, and newlib.
  docker/crosstool-config/arm-unknown-linux-gnueabihf.config
  xtask/src/crosstool.rs
Labels: enhancement, no changelog

#1095 Change Linux kernel versions from 5.x to 6.x for certain targets.
  .changes/591-1095.json
  .changes/591.json
  docker/linux-image.sh
Labels: bug, container-images, breaking change, A-powerpc, A-sparc, A-riscv

#1090 Add editorconfig file.
  .editorconfig
  .github/ISSUE_TEMPLATE/b_issue_report.yml
  .github/ISSUE_TEMPLATE/z_feature_request.yml
  ci/build_release.sh
  ci/shared.sh
  ci/test.sh
  docker/Dockerfile.aarch64-unknown-linux-gnu.centos
  docker/aarch64-linux-gnu-glibc.sh
  docker/android-ndk.sh
  docker/dragonfly.sh
  docker/dropbear.sh
  docker/freebsd.sh
  docker/linux-image.sh
  docker/mingw.sh
  docker/musl.sh
  docker/netbsd.sh
  docker/qemu.sh
  docker/solaris.sh
  xtask/src/target_info.sh
Labels: meta, no changelog

#1063 Fix linkage and C++ support for musl targets.
  .changes/1063.json
  ci/test.sh
  docker/musl-symlink.sh
  docker/musl.sh
  targets.toml
Labels: enhancement, breaking change, A-musl

#1093 Add note for custom images and arm-unknown-linux-gnueabihf.
  src/docker/shared.rs
Labels: no changelog
