Repository cross-rs/cross, pull requests merged in 2022-06, with the labels that each got.

#741 Add soft-float ARMv7 targets.
  .github/workflows/ci.yml
  CHANGELOG.md
  README.md
  docker/Dockerfile.armv7-unknown-linux-gnueabi
  docker/Dockerfile.armv7-unknown-linux-musleabi
  docker/crosstool-config/arm-unknown-linux-gnueabihf.config
Labels: enhancement, container-images, A-arm

#729 Refactor code to use install_packages and purge_packages.
  docker/Dockerfile.x86_64-unknown-linux-gnu
  docker/android-ndk.sh
  docker/android-system.sh
  docker/disabled/dragonfly.sh
  docker/emscripten.sh
  docker/freebsd.sh
  docker/linux-image.sh
  docker/mingw.sh
  docker/musl.sh
  docker/netbsd.sh
  docker/solaris.sh
Labels: no changelog

#744 Add support for multiple bors targets.
  .github/workflows/ci.yml
Labels: enhancement, no changelog

#748 Allow variable definitions in env.pasthrough.
  CHANGELOG.md
  src/docker.rs
Labels: enhancement, A-config

#749 fixup changelog
  CHANGELOG.md
Labels: no changelog

#747 Reduce Android image sizes.
  CHANGELOG.md
  docker/android-ndk.sh
Labels: enhancement, container-images, A-android

#755 Fix docker detection.
  src/docker.rs
Labels: bug, no changelog, A-container-engine

#759 update readme to mention install from git due to outdated crates version
  README.md
Labels: no changelog

#753 Add scripts to validate target info.
  ci/extract_image_info.sh
  ci/extract_target_info.sh
Labels: enhancement, no changelog

#766 add simple labels to the images
  .github/workflows/ci.yml
  build-docker-image.sh
Labels: no changelog

#684 enable cargo workspace and path dependencies to work seamlessly
  CHANGELOG.md
  README.md
  ci/test.sh
  src/cargo.rs
  src/cli.rs
  src/docker.rs
  src/file.rs
  src/main.rs
  src/tests.rs
Labels: enhancement

#762 Re-enable x86_64-unknown-dragonfly target.
  .github/workflows/ci.yml
  CHANGELOG.md
  docker/Dockerfile.x86_64-unknown-dragonfly
  docker/dragonfly.sh
Labels: enhancement, container-images, A-bsd

#767 Add cross-dev and cross-util commands.
  .github/workflows/ci.yml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  ci/extract_target_info.sh
  cross-dev/main.rs
  cross-dev/target_info.sh
  docker/dragonfly.sh
  src/bin/cross-util.rs
  src/bin/cross.rs
  src/docker.rs
  src/lib.rs
Labels: enhancement

#485 Downgrade musl to 1.1.24
  CHANGELOG.md
  README.md
  docker/musl.sh
Labels: regression, container-images, Pending: Vendor, A-musl

#768 Update README for target information.
  README.md
  cross-dev/main.rs
  cross-dev/target_info.sh
Labels: docs-problem, no changelog

#776 Bug fix for dragonfly and CI tests.
  .github/workflows/ci.yml
  ci/test.sh
  docker/dragonfly.sh
Labels: bug, no changelog, A-bsd

#775 Forward Cargo exit code
  CHANGELOG.md
  src/bin/cross.rs
Labels: enhancement

#777 Update CHANGELOG for SSH dependency support.
  CHANGELOG.md
Labels: docs-problem

#778 Fix target extraction from `rustembedded` images.
  src/bin/cross-util.rs
Labels: bug, no changelog

#774 Simplify config internals.
  src/cli.rs
  src/config.rs
  src/cross_toml.rs
  src/lib.rs
Labels: no changelog

#779 Limit calls to which to find container engine path.
  src/docker.rs
Labels: no changelog

#783 Fix clippy lints on nightly.
  src/cli.rs
  src/cross_toml.rs
  src/docker.rs
  src/lib.rs
Labels: no changelog

#780 Remove duplicate commands for mounted volumes.
  src/docker.rs
Labels: no changelog

#781 Prefer target.env values over build.env config.
  CHANGELOG.md
  src/config.rs
Labels: A-config

#772 Add `CROSS_CONTAINER_OPTS` environment variable.
  CHANGELOG.md
  src/docker.rs
Labels: enhancement

#794 Refactor docker and cross-util commands.
  src/bin/commands/images.rs
  src/bin/commands/mod.rs
  src/bin/cross-util.rs
  src/docker/engine.rs
  src/docker/local.rs
  src/docker/mod.rs
  src/docker/seccomp.json
  src/docker/shared.rs
  src/lib.rs
  xtask/src/build_docker_image.rs
  xtask/src/main.rs
Labels: no changelog

#799 Break `cross-util` into `images` subcommands.
  src/bin/commands/images.rs
  src/bin/cross-util.rs
Labels: no changelog

#800 fix typos in readme
  README.md
Labels: no changelog

#801 Make config vectors optional.
  src/config.rs
  src/cross_toml.rs
Labels: no changelog

#678 allow specifying a dockerfile to use for a target and implement "pre-build"ing
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  docs/cross_toml.md
  src/bin/commands/images.rs
  src/cargo.rs
  src/config.rs
  src/cross_toml.rs
  src/docker/custom.rs
  src/docker/local.rs
  src/docker/mod.rs
  src/docker/shared.rs
  src/extensions.rs
  src/file.rs
  src/lib.rs
  src/rustup.rs
  xtask/src/build_docker_image.rs
  xtask/src/target_info.rs
Labels: enhancement

#802 more hooks
  rustfmt.yml
  xtask/src/install_git_hooks.rs
  xtask/src/pre-commit.sh
  xtask/src/pre-push.sh
Labels: no changelog

#805 Add shellcheck to git hooks and convert to xtask.
  xtask/src/hooks.rs
  xtask/src/main.rs
  xtask/src/pre-commit.sh
  xtask/src/pre-push.sh
Labels: no changelog

#803 add `CROSS_CUSTOM_TOOLCHAIN` to disable automatic target component downloading
  CHANGELOG.md
  src/lib.rs
  src/rustup.rs
Labels: enhancement

#807 Update Qemu version to v6.1.0 if possible.
  CHANGELOG.md
  README.md
  docker/qemu.sh
Labels: enhancement, A-qemu

#806 improve error messages
  Cargo.toml
  src/cargo.rs
  src/docker/engine.rs
  src/errors.rs
  src/extensions.rs
  src/file.rs
  src/rustc.rs
  src/rustup.rs
  xtask/src/hooks.rs
Labels: no changelog

#789 build images weekly, without cache
  .github/workflows/weekly.yml
  xtask/src/build_docker_image.rs
  xtask/src/util.rs
Labels: no changelog

#811 Bug fixes for listing/removing images.
  src/bin/commands/images.rs
Labels: no changelog

#813 don't save images in weekly check
  .github/workflows/weekly.yml
  xtask/src/build_docker_image.rs
Labels: no changelog

#812 various refactors
  .github/workflows/ci.yml
  Cargo.lock
  README.md
  src/cargo.rs
  xtask/Cargo.toml
  xtask/src/build_docker_image.rs
  xtask/src/ci.rs
  xtask/src/main.rs
  xtask/src/target_info.rs
  xtask/src/util.rs
Labels: no changelog

#816 Fix wildcard and multiple selects.
  .github/workflows/ci.yml
Labels: bug, meta, no changelog

#820 Add documentation for CLI for build-docker-image.
  xtask/src/build_docker_image.rs
Labels: enhancement, meta, no changelog

#823 Minor bug fixes for target-info.
  xtask/src/target_info.rs
  xtask/src/target_info.sh
Labels: meta, no changelog

#824 Minor xtask restructuring.
  xtask/src/target_info.rs
  xtask/src/util.rs
Labels: no changelog

#825 Add a note to stderr if not executing the remove images command.
  src/bin/commands/images.rs
Labels: no changelog

#826 cleanup
  .github/workflows/ci.yml
  .github/workflows/weekly.yml
  Cargo.lock
  Cargo.toml
  LICENSE-APACHE
  LICENSE-MIT
  deny.toml
  src/docker/custom.rs
  triagebot.toml
  xtask/Cargo.toml
Labels: no changelog

#831 Fixes regression in #828 with absolute path.
  src/docker/shared.rs
Labels: regression, no changelog

#833 Fix error message with cross-util with invalid command.
  src/bin/cross-util.rs
  xtask/src/main.rs
Labels: no changelog

#834 only check msrv in clippy checks
  .github/actions/setup-rust/action.yml
  .github/workflows/ci.yml
Labels: no changelog

#836 Add a cache dir tag when creating a target directory.
  CHANGELOG.md
  src/docker/shared.rs
Labels: bug

#838 Re-enable solaris targets.
  .github/workflows/ci.yml
  CHANGELOG.md
  docker/solaris.sh
Labels: enhancement, container-images

#842 Allow `Cargo.toml` as configuration source
  CHANGELOG.md
  README.md
  docs/cross_toml.md
  src/config.rs
  src/cross_toml.rs
  src/lib.rs
  src/tests/toml.rs
Labels: enhancement

#846 Add build arguments to build-docker-image.
  xtask/src/build_docker_image.rs
Labels: enhancement, no changelog

#843 list/delete custom cross images as well
  src/bin/commands/images.rs
  src/docker/custom.rs
  src/docker/shared.rs
Labels: no changelog

#840 Re-enable wasm32-unknown-emscripten target.
  .github/workflows/ci.yml
  README.md
  docker/Dockerfile.wasm32-unknown-emscripten
  xtask/src/target_info.sh
Labels: container-images, no changelog, A-emscripten

#847 increase timeout for weekly check
  .github/workflows/weekly.yml
Labels: no changelog

#850 Formatting and bug fixes for listing images.
  src/bin/commands/images.rs
Labels: bug, regression, no changelog

#853 Update emsdk version to 3.1.14.
  README.md
  docker/Dockerfile.asmjs-unknown-emscripten
  docker/Dockerfile.wasm32-unknown-emscripten
Labels: container-images, no changelog

#837 check tag with package version early and determine if it's the latest version
  .github/workflows/ci.yml
  Cargo.lock
  xtask/Cargo.toml
  xtask/src/build_docker_image.rs
  xtask/src/ci.rs
  xtask/src/main.rs
Labels: no changelog

#856 Remove WSLpath and implement WSL-style path.
  CHANGELOG.md
  src/docker/local.rs
  src/docker/remote.rs
  src/docker/shared.rs
  src/file.rs
Labels: bug

#855 release version 0.2.2-rc.1
  Cargo.lock
  Cargo.toml
Labels: no changelog, release

#857 release v0.2.2
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: release

#867 Fix parsing of config `build.env.passthrough` values.
  CHANGELOG.md
  src/config.rs
  src/cross_toml.rs
Labels: bug, regression

#868 Ignore the `CARGO` environment variable.
  CHANGELOG.md
  src/cargo.rs
  src/docker/shared.rs
Labels: bug, regression

#869 Pass cargo configuration flags to docker.
  CHANGELOG.md
  src/docker/shared.rs
Labels: enhancement

#866 Minor refactoring in xtask.
  xtask/src/build_docker_image.rs
  xtask/src/hooks.rs
  xtask/src/install_git_hooks.rs
  xtask/src/main.rs
  xtask/src/util.rs
Labels: meta, no changelog

#859 Add cargo-style output diagnostics.
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  deny.toml
  src/bin/commands/clean.rs
  src/bin/commands/containers.rs
  src/bin/commands/images.rs
  src/bin/cross-util.rs
  src/cargo.rs
  src/cli.rs
  src/config.rs
  src/cross_toml.rs
  src/docker/custom.rs
  src/docker/engine.rs
  src/docker/local.rs
  src/docker/mod.rs
  src/docker/remote.rs
  src/docker/shared.rs
  src/extensions.rs
  src/lib.rs
  src/rustc.rs
  src/rustup.rs
  src/shell.rs
  src/tests.rs
  src/tests/toml.rs
  xtask/src/build_docker_image.rs
  xtask/src/ci.rs
  xtask/src/hooks.rs
  xtask/src/install_git_hooks.rs
  xtask/src/main.rs
  xtask/src/target_info.rs
  xtask/src/util.rs
Labels: enhancement

#876 Add unittest to verify Ubuntu base.
  xtask/src/util.rs
Labels: meta, no changelog

#829 enable coverage
  .github/actions/cargo-install-upload-artifacts/action.yml
  .github/actions/cargo-llvm-cov/action.yml
  .github/actions/cargo-publish/action.yml
  .github/actions/post/action.yml
  .github/actions/post/main.js
  .github/codecov.yml
  .github/workflows/ci.yml
  ci/test.sh
Labels: no changelog

#877 Switch crosstool-ng configure scripts to xtask.
  crosstool-ng/configure.sh
  xtask/src/crosstool.rs
  xtask/src/main.rs
  xtask/src/util.rs
Labels: meta, no changelog

#881 Update CI tests to use local cross build.
  ci/test.sh
Labels: no changelog

#882 Minor bug fixes.
  src/bin/commands/containers.rs
  xtask/src/util.rs
Labels: no changelog

#884 add some more context to error messages
  src/docker/local.rs
  src/docker/mod.rs
  src/docker/remote.rs
  src/lib.rs
Labels: no changelog
