Repository cross-rs/cross, pull requests merged in 2023-02, with the labels that each got.

#1201 Release v0.2.5
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  Dockerfile.hack
  deny.toml
  docker/Dockerfile.i686-unknown-freebsd
  docker/Dockerfile.x86_64-unknown-freebsd
  docker/dragonfly.sh
  docker/freebsd-common.sh
  docker/freebsd-extras.sh
  docker/freebsd-install.sh
  docker/freebsd.sh
  src/cross_toml.rs
  src/docker/custom.rs
  src/docker/local.rs
  src/tests/toml.rs
  xtask/src/build_docker_image.rs
Labels: release

#1199 Bugfix: use current target_dir path when copying build artifacts back
  .changes/1199.json
  src/docker/remote.rs
Labels: no-ci-targets

#1209 add commits from release v0.2.5
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: no changelog, no-ci-targets

#1207 Copy remote directories correctly
  .changes/1207.json
  src/docker/remote.rs
Labels: no-ci-targets
