Repository cross-rs/cross, pull requests merged in 2023-12, with the labels that each got.

#1385 freebsd: set PKG_CONFIG_PATH in Dockerfile
  .changes/1385.json
  docker/Dockerfile.x86_64-unknown-freebsd
Labels: no-ci-targets

#1380 feat(rootless): help detection with execv check "is current builder rootless?"
  src/docker/engine.rs
  src/docker/local.rs
  src/docker/remote.rs
  src/docker/shared.rs
Labels: no changelog, no-ci-targets

#1208 Resolve build container errors
  docker/linux-image.sh
Labels: no changelog, no-ci-targets

#1392 fix weekly check
  .github/workflows/weekly.yml
Labels: no changelog, no-ci-targets

#1393 fix linux kernel
  .changes/957-1393.json
  docker/linux-image.sh
Labels: no-ci-targets

#1394 fix mips
  ci/test.sh
  targets.toml
Labels: no changelog, no-ci-targets

#1395 use `CI-` labels to be more granular for what to run
  .github/actions/cargo-publish/action.yml
  xtask/src/build_docker_image.rs
  xtask/src/ci.rs
  xtask/src/ci/target_matrix.rs
Labels: no changelog, CI-aarch64-unknown-linux-gnu, CI-aarch64-unknown-linux-gnu.centos, CI-x86_64-unknown-linux-gnu
