Repository cross-rs/cross, pull requests merged in 2024-02, with the labels that each got.

#1430 fix composite action.yml dependabot
  .github/dependabot.yml
Labels: no changelog, no-ci-targets

#1431 allow try to specify tests, and add `no-ci-tests` label to skip tests
  .github/workflows/ci.yml
  xtask/src/ci/target_matrix.rs
  xtask/src/util.rs
Labels: no changelog, no-ci-tests

#1433 improve tests
  .github/workflows/ci.yml
  xtask/src/ci/target_matrix.rs
Labels: no changelog, no-ci-tests

#1432 disable/fix failing targets
  ci/test-zig-image.sh
  ci/test.sh
  src/docker/provided_images.rs
  targets.toml
  xtask/src/build_docker_image.rs
  xtask/src/ci/target_matrix.rs
  xtask/src/codegen.rs
  xtask/src/util.rs
Labels: no changelog

#1439 remove faulty dbg
  src/lib.rs
Labels: no changelog, no-ci-tests

#1440 fix login and publish
  .github/actions/cargo-publish/action.yml
Labels: no changelog, no-ci-targets

#1438 Docs: Restructure docs folder
  README.md
  docs/cargo_configuration.md
  docs/config_file.md
  docs/cross_toml.md
  docs/custom_images.md
  docs/environment_variables.md
  docs/getting-started.md
  docs/recipes.md
  docs/remote.md
  docs/unstable_features.md
  src/cross_toml.rs
  src/docker/engine.rs
  src/docker/image.rs
  src/lib.rs
Labels: no changelog, no-ci-tests
