Repository cross-rs/cross, pull requests merged in 2024-01, with the labels that each got.

#1406 fix try comment
  .github/workflows/ci.yml
  .github/workflows/try.yml
  .github/workflows/weekly.yml
Labels: no changelog, no-ci-targets

#1408 fix dispatch checkout-branch
  .github/workflows/ci.yml
  .github/workflows/try.yml
  .github/workflows/weekly.yml
Labels: no changelog, no-ci-targets

#1405 Fix `docker/linux-image.sh` script
  .changes/1399.json
  .gitignore
  CHANGELOG.md
  docker/linux-image.sh
Labels: CI-powerpc-unknown-linux-gnu, CI-powerpc64-unknown-linux-gnu

#1410 Make try comment prettier
  .github/workflows/ci.yml
  .github/workflows/try.yml
Labels: no changelog, no-ci-targets

#1407 make `mips-unknown-linux-musl` and `mipsel-unknown-linux-musl` use build-std in ci
  targets.toml
Labels: no changelog, no-ci-targets

#1403 Switch to FreeBSD 13.2
  .changes/1390.json
  docker/Dockerfile.aarch64-unknown-freebsd
  docker/Dockerfile.i686-unknown-freebsd
  docker/Dockerfile.x86_64-unknown-freebsd
  docker/freebsd-common.sh
  docker/freebsd-fetch-best-mirror.sh
  docker/freebsd-install-package.sh
  docker/freebsd-setup-packagesite.sh
  docker/freebsd.sh
Labels: CI-aarch64-unknown-freebsd, CI-i686-unknown-freebsd, CI-x86_64-unknown-freebsd

#1414 some xtask changes
  .github/workflows/changelog.yml
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  clippy.toml
  src/docker/image.rs
  src/docker/shared.rs
  src/errors.rs
  src/shell.rs
  xtask/src/build_docker_image.rs
  xtask/src/changelog.rs
  xtask/src/hooks.rs
  xtask/src/main.rs
  xtask/src/util.rs
Labels: no changelog, no-ci-targets

#1415 Setting PKG_CONFIG_ALLOW_CROSS=1 inside dockerfiles
  docker/Dockerfile.aarch64-unknown-linux-gnu
  docker/Dockerfile.arm-unknown-linux-gnueabi
  docker/Dockerfile.arm-unknown-linux-gnueabihf
  docker/Dockerfile.armv5te-unknown-linux-gnueabi
  docker/Dockerfile.armv7-unknown-linux-gnueabi
  docker/Dockerfile.armv7-unknown-linux-gnueabihf
  docker/Dockerfile.i586-unknown-linux-gnu
  docker/Dockerfile.i686-unknown-linux-gnu
  docker/Dockerfile.mips-unknown-linux-gnu
  docker/Dockerfile.mips64-unknown-linux-gnuabi64
  docker/Dockerfile.mips64el-unknown-linux-gnuabi64
  docker/Dockerfile.mipsel-unknown-linux-gnu
  docker/Dockerfile.powerpc-unknown-linux-gnu
  docker/Dockerfile.powerpc64-unknown-linux-gnu
  docker/Dockerfile.powerpc64le-unknown-linux-gnu
  docker/Dockerfile.riscv64gc-unknown-linux-gnu
  docker/Dockerfile.s390x-unknown-linux-gnu
  docker/Dockerfile.sparc64-unknown-linux-gnu
  docker/Dockerfile.thumbv7neon-unknown-linux-gnueabihf
  docker/Dockerfile.x86_64-unknown-freebsd
  docker/Dockerfile.x86_64-unknown-linux-gnu
  src/docker/shared.rs
Labels: no changelog, no-ci-targets

#1418 Add GCC_CONFIG option to enable default PIE
  docker/musl.sh
Labels: no changelog, A-musl, CI-aarch64-unknown-linux-musl, CI-arm-unknown-linux-musleabi, CI-arm-unknown-linux-musleabihf, CI-armv5te-unknown-linux-musleabi, CI-armv7-unknown-linux-musleabi, CI-armv7-unknown-linux-musleabihf, CI-i586-unknown-linux-musl, CI-i686-unknown-linux-musl, CI-x86_64-unknown-linux-musl

#1421 make a newline on ack
  .github/workflows/try.yml
Labels: no changelog, no-ci-targets

#1391 Add `-idirafter/usr/include` to bindgen's clang invocation on GNU/Linux
  .changes/1391.json
  docker/Dockerfile.aarch64-unknown-linux-gnu
  docker/Dockerfile.arm-unknown-linux-gnueabi
  docker/Dockerfile.arm-unknown-linux-gnueabihf
  docker/Dockerfile.armv5te-unknown-linux-gnueabi
  docker/Dockerfile.armv7-unknown-linux-gnueabi
  docker/Dockerfile.armv7-unknown-linux-gnueabihf
  docker/Dockerfile.i586-unknown-linux-gnu
  docker/Dockerfile.i686-pc-windows-gnu
  docker/Dockerfile.i686-unknown-linux-gnu
  docker/Dockerfile.mips-unknown-linux-gnu
  docker/Dockerfile.mips64-unknown-linux-gnuabi64
  docker/Dockerfile.mips64el-unknown-linux-gnuabi64
  docker/Dockerfile.mipsel-unknown-linux-gnu
  docker/Dockerfile.powerpc-unknown-linux-gnu
  docker/Dockerfile.powerpc64-unknown-linux-gnu
  docker/Dockerfile.powerpc64le-unknown-linux-gnu
  docker/Dockerfile.riscv64gc-unknown-linux-gnu
  docker/Dockerfile.s390x-unknown-linux-gnu
  docker/Dockerfile.sparc64-unknown-linux-gnu
  docker/Dockerfile.thumbv7neon-unknown-linux-gnueabihf
  docker/Dockerfile.x86_64-pc-windows-gnu
  docker/Dockerfile.x86_64-unknown-linux-gnu
Labels: no-ci-targets

#1159 metadata config
  .changes/1159.json
  Cargo.toml
  src/bin/commands/run.rs
  src/cargo.rs
  src/config.rs
  src/cross_toml.rs
  src/lib.rs
  src/tests/toml.rs
Labels: no-ci-targets

#661 panic when image does not exist, warnings/errors have been emitted and running on CI or with `CROSS_NO_WARNINGS=1`
  .changes/661.json
  Cargo.lock
  Cargo.toml
  src/bin/cross.rs
  src/docker/local.rs
  src/docker/mod.rs
  src/docker/remote.rs
  src/lib.rs
  src/shell.rs
Labels: enhancement, breaking change, no-ci-targets

#1426 improve changelog xtask
  .changes/1403-1411.json
  .github/workflows/changelog.yml
  xtask/src/changelog.rs
Labels: no-ci-targets

#1427 run matrix build on weekly schedule
  .github/workflows/ci.yml
Labels: no changelog, no-ci-targets

#1428 Create dependabot.yml
  .github/dependabot.yml
Labels: no changelog, no-ci-targets
