Repository cross-rs/cross, pull requests merged in 2024-05, with the labels that each got.

#1484 Update `taiki-e/install-action` to `v2`
  .github/actions/cargo-llvm-cov/action.yml
Labels: no changelog, CI-x86_64-unknown-linux-gnu

#1483 Fix paths when using `CROSS_CONTAINER_IN_CONTAINER`
  .changes/1483.json
  src/docker/local.rs
  src/docker/shared.rs
Labels: no-ci-targets

#1485 Use `/proc/self/mountinfo` as a fallback for `docker inspect` if using `HOSTNAME` fails
  .changes/1485.json
  src/docker/shared.rs
Labels: no-ci-targets

#1488 Allow `build-std` to take an array of crate names
  .changes/1488.json
  docs/config_file.md
  src/config.rs
  src/cross_toml.rs
  src/lib.rs
Labels: no-ci-targets

#1490 bump wine to 9
  .changes/1374-1490.json
  docker/wine.sh
Labels: CI-i686-pc-windows-gnu, CI-x86_64-pc-windows-gnu

#1495 Fix `*-solaris` targets
  .changes/1495.json
  .github/ISSUE_TEMPLATE/b_issue_report.yml
  README.md
  docker/Dockerfile.sparcv9-sun-solaris
  docker/Dockerfile.x86_64-pc-solaris
  docker/Dockerfile.x86_64-sun-solaris
  docker/solaris.sh
  src/docker/provided_images.rs
  src/lib.rs
  targets.toml
Labels: CI-sparcv9-sun-solaris, CI-x86_64-pc-solaris
