Repository cross-rs/cross, pull requests merged in 2025-02, with the labels that each got.

#1623 don't look at `package.metadata.cross` when the package isn't part of the current workspace
  .changes/1623.json
  deny.toml
  src/lib.rs
Labels: no-ci-targets

#1626 fix linux images
  .github/actions/cargo-install-upload-artifacts/action.yml
  .github/actions/cargo-publish/action.yml
  .github/workflows/ci.yml
  docker/Dockerfile.aarch64-unknown-linux-gnu.centos
  docker/Dockerfile.native.centos
  docker/linux-image.sh
Labels: no changelog, no-ci-targets

#1625 Bump ct-ng to 1.27.0
  .changes/1625.json
  docker/Dockerfile.loongarch64-unknown-linux-gnu
  docker/Dockerfile.loongarch64-unknown-linux-musl
  docker/crosstool-ng.sh
Labels: CI-arm-unknown-linux-gnueabihf, no-ci-tests, CI-loongarch64-unknown-linux-gnu, CI-loongarch64-unknown-linux-musl
